# Generated by Django 5.0.3 on 2024-04-19 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0003_alter_avatar_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='user',
            new_name='username',
        ),
    ]
