# Generated by Django 5.0.3 on 2024-04-19 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0004_rename_user_avatar_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='imagen',
            new_name='image',
        ),
    ]
