# Generated by Django 5.0.3 on 2024-04-19 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0006_alter_avatar_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='username',
            new_name='user',
        ),
    ]
